In [1]:
import numpy as np

In [4]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [5]:
b=[[1,2,3,4,5],[6,7,8,9,10]]
b

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
a_array=np.array(a)
a_array

array([1, 2, 3, 4, 5])

In [8]:
b_array=np.array(b)
b_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
c_array=np.array([1,2,3,4,5])
c_array

array([1, 2, 3, 4, 5])

In [16]:
add_array= a_array + c_array
add_array

array([ 2,  4,  6,  8, 10])

In [19]:
add1_array= a_array -c_array
add1_array

array([0, 0, 0, 0, 0])

In [20]:
add3_array= a_array * c_array
add3_array

array([ 1,  4,  9, 16, 25])

In [23]:
b_array.shape

(2, 5)

In [24]:
c_array.sum()

15

In [25]:
c_array.mean()

3.0

In [26]:
b_array[1,4]

10

In [27]:
b_array[:,:]
b_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
b_array[:,4]

array([ 5, 10])

In [29]:
b_array[0,:]
b_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
x=np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [35]:
y=np.linspace(0,10,5)
y

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
z=np.diag([1,2,3])
z

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [47]:
a=np.random.rand(3,2)
a

array([[0.62518963, 0.81718642],
       [0.43020958, 0.73593223],
       [0.24650331, 0.22285174]])

In [45]:
a.reshape(2,3)

array([[0.91568574, 0.12593657, 0.48833448],
       [0.85008487, 0.41796093, 0.87435187]])

In [48]:
a=[[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [52]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])